name: Montara CI

on:
  push:
    branches:
      - master

jobs:
  montara:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Montara
        uses: montara-io/montara-ci@v1.0.20
        with:
          webhookUrl: ${{ secrets.MONTARA_WEBHOOK_URL }}
          isSmartRun: true
          allowConcurrentPipelineRuns: true
          numRetries: 60
